[package]
name = "filematch"
version = "0.1.0"
authors = ["Rein F <public@reinfernhout.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md-5 = "0.9.1"
hex = "0.3.1"
